version: '3.3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME} 
  redis:
    image: "redis:alpine"
  
  celery:
    build: .
    command: celery -A un_alternant_une_solution_webapp worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A un_alternant_une_solution_webapp beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
volumes:
  redis_data:
    driver: local