# Generated by Django 4.0.3 on 2022-03-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_codes', models.ManyToManyField(related_name='course_job_codes+', to='job.jobcode')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_school+', to='authentication.school')),
            ],
        ),
    ]
