# Generated by Django 4.0.3 on 2022-03-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_school_courses'),
        ('course', '0002_course_create_at_course_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_school+', to='authentication.school'),
            preserve_default=False,
        ),
    ]
