# Generated by Django 4.0.3 on 2022-03-17 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '__first__'),
        ('authentication', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Profession Name')),
                ('code', models.IntegerField(verbose_name='Profession Code')),
            ],
            options={
                'db_table': 'profession',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Profession Name')),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='JobDating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_letter_path', models.CharField(max_length=255, verbose_name='Job Name')),
                ('cv_path', models.CharField(max_length=255, verbose_name='Job Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
            options={
                'db_table': 'jobDating',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Course Name')),
                ('description', models.TextField(verbose_name='Course Description')),
                ('listProfessions', models.ManyToManyField(to='app.profession')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
