# Generated by Django 4.0.3 on 2022-03-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Profession Name')),
                ('code', models.IntegerField(verbose_name='Profession Code')),
            ],
            options={
                'db_table': 'profession',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Course Name')),
                ('description', models.TextField(verbose_name='Course Description')),
                ('listProfessions', models.ManyToManyField(to='app.profession')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
