# Generated by Django 4.0.3 on 2022-03-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='JobCode',
        ),
    ]
