# Generated by Django 4.0.3 on 2022-03-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='listProfessions',
            field=models.ManyToManyField(to='app.profession'),
        ),
    ]
