# Generated by Django 4.0.3 on 2022-03-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_job_jobcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobcode',
            table='job_code',
        ),
    ]
