# Generated by Django 4.0.3 on 2022-03-18 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(null=True, verbose_name='School Description'),
        ),
        migrations.AddField(
            model_name='school',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
        migrations.AlterModelTable(
            name='school',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
