# Generated by Django 4.0.3 on 2022-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=75, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(null=True, verbose_name='Company Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(max_length=75, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(max_length=75, null=True, verbose_name='Zip Code'),
        ),
    ]
