# Generated by Django 4.0.3 on 2022-03-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user_companies',
            new_name='users',
        ),
    ]
