# Generated by Django 4.0.3 on 2022-03-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='extension_picture',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Picture Extension'),
        ),
        migrations.AddField(
            model_name='school',
            name='extension_picture',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Picture Extension'),
        ),
    ]
