# Generated by Django 4.0.3 on 2022-03-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_company_city_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cv_path',
            field=models.CharField(max_length=255, null=True, verbose_name='CV Path'),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin_url',
            field=models.URLField(null=True, verbose_name='LinkedIn URL'),
        ),
    ]
