# Generated by Django 4.0.3 on 2022-03-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_school_create_at_school_description_school_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=150, verbose_name='School Name'),
        ),
    ]
