# Generated by Django 3.2.8 on 2022-03-05 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220305_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=75, verbose_name='Last Name')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('linkedin_url', models.URLField(verbose_name='LinkedIn URL')),
                ('cv_path', models.CharField(max_length=255, verbose_name='CV Path')),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Company Name')),
                ('description', models.TextField(verbose_name='Company Description')),
                ('city', models.CharField(max_length=75, verbose_name='City')),
                ('street', models.CharField(max_length=75, verbose_name='Street')),
                ('zip_code', models.CharField(max_length=75, verbose_name='Zip Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
