# Generated by Django 4.0.3 on 2022-03-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_school_create_at_school_description_school_update_at_and_more'),
        ('authentication', '0002_school_description'),
    ]

    operations = [
    ]
