# Generated by Django 4.0.3 on 2022-03-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_jobidfrompreviousrequest_job_codes_and_more'),
        ('authentication', '0003_alter_student_birthday_alter_student_cv_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='jobs',
            field=models.ManyToManyField(related_name='company_jobs+', to='job.job'),
        ),
    ]
