# Generated by Django 4.0.3 on 2022-03-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_company_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(null=True, verbose_name='School Description'),
        ),
        migrations.AddField(
            model_name='user',
            name='extension_picture',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Picture Extension'),
        ),
    ]
