# Generated by Django 4.0.3 on 2022-03-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('wage', models.FloatField()),
                ('contract_type', models.CharField(choices=[('AL', 'Alternance'), ('IN', 'Internship'), ('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('VO', 'Volunteer'), ('OT', 'Other')], max_length=2)),
                ('start_date', models.DateField()),
                ('schedule', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed'), ('CA', 'Canceled')], max_length=2)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
            options={
                'db_table': 'job_status',
            },
        ),
    ]
