# Generated by Django 4.0.3 on 2022-03-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_school_courses_school_users"),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdating",
            name="job",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="job.job"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobdating",
            name="student",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.student",
            ),
            preserve_default=False,
        ),
    ]
