# Generated by Django 4.0.3 on 2022-03-18 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_school_create_at_school_description_school_update_at_and_more'),
        ('job', '0002_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobidfrompreviousrequest',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lastindexapi',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jobcode',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jobidfrompreviousrequest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jobstatus',
            table=None,
        ),
        migrations.AlterModelTable(
            name='lastindexapi',
            table=None,
        ),
        migrations.CreateModel(
            name='JobDating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_letter_path', models.CharField(max_length=255, verbose_name='Job Name')),
                ('cv_path', models.CharField(max_length=255, verbose_name='Job Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobstatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
