# Generated by Django 4.0.3 on 2022-03-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobdating_job_jobdating_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='job',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
            preserve_default=False,
        ),
    ]
