# Generated by Django 4.0.3 on 2022-03-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcode',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
