# Generated by Django 4.0.3 on 2022-03-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_lastindexapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='api_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='contract_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='wage',
            field=models.FloatField(null=True),
        ),
    ]
