# Generated by Django 4.0.3 on 2022-03-17 07:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_api_id_alter_job_contract_type_alter_job_wage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIdFromPreviousRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_codes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('job_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'db_table': 'job_id_from_previous_request',
            },
        ),
    ]
