# Generated by Django 4.0.3 on 2022-03-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdating',
            name='status',
            field=models.CharField(choices=[('AC', 'ACCEPTED'), ('RE', 'REJECTED'), ('PE', 'PENDING')], max_length=2),
        ),
    ]
