# Generated by Django 4.0.3 on 2022-03-17 07:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobidfrompreviousrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobidfrompreviousrequest',
            name='job_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='jobidfrompreviousrequest',
            name='job_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
