# Generated by Django 4.0.3 on 2022-03-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_jobdating_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdating',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='authentication/files/cv'),
        ),
        migrations.AddField(
            model_name='jobdating',
            name='motivation_letter',
            field=models.FileField(blank=True, null=True, upload_to='authentication/files/motivation_letter'),
        ),
    ]
