# Generated by Django 4.0.3 on 2022-03-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_company_jobs'),
        ('job', '0007_alter_jobidfrompreviousrequest_job_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='job_company+', to='authentication.company'),
            preserve_default=False,
        ),
    ]
