# Generated by Django 4.0.3 on 2022-03-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_jobdating_cv_jobdating_motivation_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdating',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='job/files/cv'),
        ),
        migrations.AlterField(
            model_name='jobdating',
            name='motivation_letter',
            field=models.FileField(blank=True, null=True, upload_to='job/files/motivation_letter'),
        ),
    ]
