name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  DATABASE_PASSWORD: 3fc5ed1833891f062798111a97d4a4396b670c16a2ea614a6b8d4093ce442f27
  DATABASE_NAME: d6ciu6qsd262o4
  DATABASE_USER: hojkcrjpjxpkth
  DATABASE_HOST: ec2-176-34-105-15.eu-west-1.compute.amazonaws.com
  DATABASE_PORT: 5432
  PORT: 5000

jobs:
  health-check-job: 
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2
      - name: Cache dependency # caching dependency will make our build faster.
        uses: actions/cache@v2 # for more info checkout pip section documentation at https://github.com/actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup python environment # setting python environment to 3.x
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }} # if you want multiple python version run just use matrix strategy in job config. See the documentation of GitHub Actions
      - name: Check Python version # checking the python version to see if 3.x is installed.
        run: python --version
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check Syntax # check code formatting
        run: pycodestyle --statistics --ignore=E501 .
      - name: Run Migrations # run migrations to create table in side car db container
        run: python manage.py migrate
      - name: Run Tests
        run: |
          python manage.py test
